# -*- coding: utf-8 -*-
"""Copy of Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17h_bpnf-0FAUEygXItQnuWbDy4Yw4CtG

1.FCFS CPU Scheduling

FCFS using hard-coded variables
"""

bt = [5, 3, 8]   # burst times
n = len(bt)

ct = 0
wt_total = 0
tat_total = 0

print("Process  BT  CT  WT  TAT")
for i in range(n):
    ct += bt[i]
    tat = ct
    wt = tat - bt[i]
    wt_total += wt
    tat_total += tat
    print(f"P{i+1}     {bt[i]}   {ct}   {wt}   {tat}")

print("Average WT =", wt_total/n)
print("Average TAT =", tat_total/n)

"""FCFS using keyboard input"""

# FCFS using keyboard input
n = int(input("Enter number of processes: "))
bt = []

for i in range(n):
    bt.append(int(input(f"Enter burst time for P{i+1}: ")))

ct = 0
print("\nProcess  BT  CT  WT  TAT")
for i in range(n):
    ct += bt[i]
    tat = ct
    wt = tat - bt[i]
    print(f"P{i+1}     {bt[i]}   {ct}   {wt}   {tat}")

"""FIFO – Read from File (Single Set)"""

from google.colab import files
uploaded = files.upload()

with open("fifo_input.txt", "r") as f:
    frames = int(f.readline())
    pages = list(map(int, f.readline().split()))

memory = []
faults = 0

for p in pages:
    if p not in memory:
        faults += 1
        if len(memory) < frames:
            memory.append(p)
        else:
            memory.pop(0)
            memory.append(p)
    print(memory)

print("Total Page Faults:", faults)

"""FIFO – Read from File (Multiple Sets)"""

from google.colab import files
uploaded = files.upload()

with open("fifo_multi.txt", "r") as f:
    while True:
        line = f.readline()

        # stop if end of file
        if not line:
            break

        # skip empty lines
        line = line.strip()
        if line == "":
            continue

        frames = int(line)
        pages = list(map(int, f.readline().split()))

        memory = []
        faults = 0

        print("\nNew Input Set")

        for p in pages:
            if p not in memory:
                faults += 1
                if len(memory) < frames:
                    memory.append(p)
                else:
                    memory.pop(0)
                    memory.append(p)
            print(memory)

        print("Faults:", faults)

"""2.READERS – WRITERS PROBLEM

Readers–Writers Hard-Coded variable
"""

readers = 0

def reader():
    global readers
    readers += 1
    print("Reader is reading")
    readers -= 1

def writer():
    print("Writer is writing")

reader()
reader()
writer()

"""Readers–Writers Keyboard Input"""

readers = 0

n = int(input("Enter number of readers: "))
m = int(input("Enter number of writers: "))

for i in range(n):
    readers += 1
    print(f"Reader {i+1} is reading")
    readers -= 1

for i in range(m):
    print(f"Writer {i+1} is writing")

"""Readers–Writers Read from File (Single Set)"""

from google.colab import files
uploaded = files.upload()

with open("rw_input.txt", "r") as f:
    readers_count = int(f.readline())
    writers_count = int(f.readline())

for i in range(readers_count):
    print(f"Reader {i+1} is reading")

for i in range(writers_count):
    print(f"Writer {i+1} is writing")

"""Readers–Writers Read from File (Multiple Sets)"""

from google.colab import files
uploaded = files.upload()

with open("rw_multi.txt", "r") as f:
    while True:
        r = f.readline()

        # stop at end of file
        if not r:
            break

        # remove spaces and newline
        r = r.strip()

        # skip empty lines
        if r == "":
            continue

        readers_count = int(r)
        writers_count = int(f.readline().strip())

        print("\nNew Set")
        for i in range(readers_count):
            print(f"Reader {i+1} is reading")

        for i in range(writers_count):
            print(f"Writer {i+1} is writing")

"""3. ROUND ROBIN SCHEDULING

Round Robin Hard-Coded variables
"""

bt = [5, 4, 2]
tq = 2
n = len(bt)

rem_bt = bt.copy()
wt = [0]*n
time = 0

while True:
    done = True
    for i in range(n):
        if rem_bt[i] > 0:
            done = False
            if rem_bt[i] > tq:
                time += tq
                rem_bt[i] -= tq
            else:
                time += rem_bt[i]
                wt[i] = time - bt[i]
                rem_bt[i] = 0
    if done:
        break

tat = [bt[i] + wt[i] for i in range(n)]

print("WT:", wt)
print("TAT:", tat)

"""Round Robin Keyboard Input"""

n = int(input("Enter number of processes: "))
bt = []

for i in range(n):
    bt.append(int(input(f"Enter burst time for P{i+1}: ")))

tq = int(input("Enter time quantum: "))

rem_bt = bt.copy()
wt = [0]*n
time = 0

while True:
    done = True
    for i in range(n):
        if rem_bt[i] > 0:
            done = False
            if rem_bt[i] > tq:
                time += tq
                rem_bt[i] -= tq
            else:
                time += rem_bt[i]
                wt[i] = time - bt[i]
                rem_bt[i] = 0
    if done:
        break

tat = [bt[i] + wt[i] for i in range(n)]

print("\nWT:", wt)
print("TAT:", tat)
print("Average WT =", sum(wt)/n)
print("Average TAT =", sum(tat)/n)

"""Round Robin Read from File (Single Set)"""

from google.colab import files
uploaded = files.upload()

n = int(input())
bt = list(map(int, input().split()))
tq = int(input())

rem = bt[:]
wt = [0]*n
time = 0

while True:
    done = True
    for i in range(n):
        if rem[i] > 0:
            done = False
            x = min(tq, rem[i])
            time += x
            rem[i] -= x
            if rem[i] == 0:
                wt[i] = time - bt[i]
    if done:
        break

print("WT:", wt)
print("TAT:", [bt[i] + wt[i] for i in range(n)])

"""Round Robin Read from File (Multiple Sets)"""

from google.colab import files
uploaded = files.upload()

with open("rr_multi.txt", "r") as f:
    while True:
        line = f.readline()

        # end of file
        if not line:
            break

        # remove spaces and newline
        line = line.strip()

        # skip empty lines
        if line == "":
            continue

        n = int(line)

        # read burst times (skip empty lines if any)
        bt_line = f.readline().strip()
        while bt_line == "":
            bt_line = f.readline().strip()
        bt = list(map(int, bt_line.split()))

        # read time quantum (skip empty lines if any)
        tq_line = f.readline().strip()
        while tq_line == "":
            tq_line = f.readline().strip()
        tq = int(tq_line)

        rem = bt.copy()
        wt = [0] * n
        time = 0

        while any(rem):
            for i in range(n):
                if rem[i] > 0:
                    x = min(tq, rem[i])
                    time += x
                    rem[i] -= x
                    if rem[i] == 0:
                        wt[i] = time - bt[i]

        tat = [bt[i] + wt[i] for i in range(n)]

        print("\nNew Set")
        print("WT:", wt)
        print("TAT:", tat)